// <auto-generated />
using LifeTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815224247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeTracker.StationMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float?>("AirPressure")
                        .HasColumnType("real")
                        .HasJsonPropertyName("airpressure");

                    b.Property<float?>("Humidity")
                        .HasColumnType("real")
                        .HasJsonPropertyName("humidity");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("stationid");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("stationname");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real")
                        .HasJsonPropertyName("temperature");

                    b.Property<float?>("WindspeedBft")
                        .HasColumnType("real")
                        .HasJsonPropertyName("windspeedBft");

                    b.HasKey("ID");

                    b.ToTable("WeatherLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
