// <auto-generated />
using System;
using LifeTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeTracker.Entities.ActivityWatch.ActivityEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("App")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AwID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("ActivityWatchEvents");
                });

            modelBuilder.Entity("LifeTracker.Entities.ESP32.BuienradarStationMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float?>("AirPressure")
                        .HasColumnType("real")
                        .HasColumnOrder(13)
                        .HasJsonPropertyName("airpressure");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(15);

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnOrder(6)
                        .HasJsonPropertyName("humidity");

                    b.Property<float?>("Precipitation")
                        .HasColumnType("real")
                        .HasColumnOrder(8)
                        .HasJsonPropertyName("precipitation");

                    b.Property<float?>("RainFallLast24Hour")
                        .HasColumnType("real")
                        .HasColumnOrder(11)
                        .HasJsonPropertyName("rainFallLast24Hour");

                    b.Property<float?>("RainFallLastHour")
                        .HasColumnType("real")
                        .HasColumnOrder(10)
                        .HasJsonPropertyName("rainFallLastHour");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnOrder(2)
                        .HasJsonPropertyName("stationid");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(3)
                        .HasJsonPropertyName("stationname");

                    b.Property<float?>("SunPower")
                        .HasColumnType("real")
                        .HasColumnOrder(9)
                        .HasJsonPropertyName("sunpower");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnOrder(5)
                        .HasJsonPropertyName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(16);

                    b.Property<string>("WeatherDescription")
                        .HasColumnType("text")
                        .HasColumnOrder(4)
                        .HasJsonPropertyName("weatherdescription");

                    b.Property<string>("WindDirection")
                        .HasColumnType("text")
                        .HasColumnOrder(7)
                        .HasJsonPropertyName("winddirection");

                    b.Property<float?>("WindspeedBft")
                        .HasColumnType("real")
                        .HasColumnOrder(12)
                        .HasJsonPropertyName("windspeedBft");

                    b.HasKey("ID");

                    b.ToTable("BuienradarStationMeasurements");
                });

            modelBuilder.Entity("LifeTracker.Entities.ESP32.RoomClimateMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CO2")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(6);

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnOrder(5)
                        .HasJsonPropertyName("humidity");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnOrder(4)
                        .HasJsonPropertyName("temperature");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(7);

                    b.HasKey("ID");

                    b.ToTable("RoomClimateMeasurements");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailyHeartRate", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<int>("Min")
                        .HasColumnType("integer");

                    b.Property<int>("RestingRate")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Date");

                    b.ToTable("DailyHeartRates");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailySleep", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("AvgHeartRate")
                        .HasColumnType("integer");

                    b.Property<int>("AvgSleepStress")
                        .HasColumnType("integer");

                    b.Property<int>("AwakeSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeepSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("LightSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RemSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SleepTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Date");

                    b.ToTable("DailySleeps");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailyStress", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Average")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Date");

                    b.ToTable("DailyStresses");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.HeartRateSample", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BPM")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Sleeping")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Date", "Timestamp");

                    b.ToTable("HeartRateSamples");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.HeartRateSample", b =>
                {
                    b.HasOne("LifeTracker.Entities.Garmin.DailyHeartRate", "DailyHeartRate")
                        .WithMany("Samples")
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyHeartRate");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailyHeartRate", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
