// <auto-generated />
using System;
using LifeTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeTracker.Entities.ActivityWatch.ActivityEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("App")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AwID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("ActivityWatchEvents");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailyHeartRate", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Max")
                        .HasColumnType("integer");

                    b.Property<int?>("Min")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingRate")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("DailyHeartRate");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailySleep", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("AvgHeartRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("AvgSleepStress")
                        .HasColumnType("double precision");

                    b.Property<int>("AwakeSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DeepSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("LightSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RemSleepSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SleepTimeSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("DailySleep");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailyStress", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("Average")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Max")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("DailyStress");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.HeartRateSample", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BPM")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("Sleeping")
                        .HasColumnType("boolean");

                    b.HasKey("Date", "Timestamp");

                    b.ToTable("HeartRateSample");
                });

            modelBuilder.Entity("LifeTracker.Services.StationMeasurement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<float?>("AirPressure")
                        .HasColumnType("real")
                        .HasJsonPropertyName("airpressure");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<float?>("Humidity")
                        .HasColumnType("real")
                        .HasJsonPropertyName("humidity");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("stationid");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("stationname");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real")
                        .HasJsonPropertyName("temperature");

                    b.Property<float?>("WindspeedBft")
                        .HasColumnType("real")
                        .HasJsonPropertyName("windspeedBft");

                    b.HasKey("ID");

                    b.ToTable("WeatherLogs");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.HeartRateSample", b =>
                {
                    b.HasOne("LifeTracker.Entities.Garmin.DailyHeartRate", "DailyHeartRate")
                        .WithMany("Samples")
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyHeartRate");
                });

            modelBuilder.Entity("LifeTracker.Entities.Garmin.DailyHeartRate", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
